import { text as t, type GameRule } from './types.ts';

export const pokerCasinoRules: Record<string, GameRule> = {
  holdem: { deck:t('52 карты','52 cards'), goal:t('Собрать лучшую пятикарточную покерную комбинацию.','Make the best five-card poker hand.'), setup:t('Каждому дают 2 закрытые карты; 5 общих открываются в центре.','Each player gets 2 hole cards; 5 community cards are revealed.'), steps:[t('Раунды ставок идут до флопа, после флопа, тёрна и ривера.','Betting occurs before the flop and after the flop, turn and river.'),t('Можно использовать любую комбинацию своих и общих карт.','Use any combination of hole and community cards.'),t('Банк выигрывает последняя оставшаяся ставка или лучшая рука на вскрытии.','The last unopposed player or best showdown hand wins the pot.')]},
  omaha: { deck:t('52 карты','52 cards'), goal:t('Собрать лучшую пятикарточную комбинацию.','Make the best five-card hand.'), setup:t('Каждому дают 4 закрытые карты, на стол выходят 5 общих.','Each player gets 4 hole cards and shares 5 community cards.'), steps:[t('Ставки проходят как в холдеме: префлоп, флоп, тёрн, ривер.','Bet preflop, flop, turn and river as in Hold’em.'),t('В комбинации обязаны быть ровно 2 свои и ровно 3 общие карты.','A hand must use exactly 2 hole cards and exactly 3 board cards.'),t('Лучшая комбинация забирает банк.','The best hand takes the pot.')]},
  'five-draw': { deck:t('52 карты','52 cards'), goal:t('Получить лучшую пятикарточную комбинацию.','Make the best five-card poker hand.'), setup:t('Каждому раздают 5 закрытых карт.','Deal 5 private cards to each player.'), steps:[t('После первого круга ставок можно заменить выбранные карты.','After the first betting round, exchange selected cards.'),t('Затем проходит последний круг ставок.','A final betting round follows.'),t('Оставшиеся игроки вскрываются; лучшая рука выигрывает.','Remaining players reveal; the best hand wins.')]},
  'five-stud': { deck:t('52 карты','52 cards'), goal:t('Собрать лучшую комбинацию из пяти карт.','Make the best five-card poker hand.'), setup:t('Первая карта закрытая, остальные выдаются открытыми по одной.','The first card is down; remaining cards are dealt face up one at a time.'), steps:[t('После каждой новой карты проходит круг ставок.','A betting round follows each new card.'),t('Порядок первого хода определяется видимыми картами.','Visible cards determine who acts first.'),t('После пятой карты лучшая рука на вскрытии забирает банк.','After the fifth card, the best showdown hand wins.')]},
  chinese: { deck:t('52 карты','52 cards'), goal:t('Разложить 13 карт в три руки сильнее рук соперника.','Arrange 13 cards into three rows stronger than the opponent’s.'), setup:t('Каждый получает 13 карт и раскладывает: 3 впереди, по 5 в середине и сзади.','Each player gets 13 cards: 3 in front, 5 middle and 5 back.'), steps:[t('Задняя рука должна быть не слабее средней, средняя — не слабее передней.','Back must be at least as strong as middle, and middle as front.'),t('Соответствующие ряды игроков сравниваются отдельно.','Matching rows are compared separately.'),t('За выигранные ряды и специальные комбинации начисляются очки.','Score points for won rows and special combinations.')]},
  'short-deck': { deck:t('36 карт','36 cards'), goal:t('Выиграть банк лучшей рукой или ставкой без ответа.','Win the pot with the best hand or an uncalled bet.'), setup:t('Играют без карт 2–5; каждому дают 2 закрытые и открывают 5 общих.','Remove ranks 2–5; deal 2 hole cards and 5 community cards.'), steps:[t('Ставки проходят как в техасском холдеме.','Betting follows Texas Hold’em.'),t('Туз может быть младшим в стрите A-6-7-8-9.','An ace can be low in A-6-7-8-9.'),t('В Cardix флеш старше фул-хауса из-за укороченной колоды.','In Cardix, a flush beats a full house because of the short deck.')]},
  blackjack: { deck:t('52 карты','52 cards'), goal:t('Победить дилера суммой ближе к 21 без перебора.','Beat the dealer with a total closer to 21 without busting.'), setup:t('Игрок и дилер получают по 2 карты; одна карта дилера закрыта.','Player and dealer receive 2 cards; one dealer card is hidden.'), steps:[t('Берите карту, остановитесь или удвойте ставку.','Hit, stand or double down.'),t('Дилер берёт до 17 и затем останавливается.','Dealer draws to 17 and then stands.'),t('Блэкджек — туз и карта ценностью 10; перебор проигрывает.','Blackjack is an ace plus a ten-value card; a bust loses.')]},
  baccarat: { deck:t('6–8 колод','6–8 decks'), goal:t('Угадать, чья рука ближе к 9: игрока или банкира.','Bet on Player or Banker finishing closer to 9.'), setup:t('Обе стороны получают по 2 карты. Десятки и картинки дают 0, туз — 1; учитывается последняя цифра суммы.','Both sides get 2 cards. Tens and faces are 0, aces 1; only the last digit counts.'), steps:[t('Выберите ставку: Игрок, Банкир или Ничья.','Bet on Player, Banker or Tie.'),t('Третья карта выдаётся автоматически по таблице правил.','A third card is drawn automatically according to fixed rules.'),t('Рука ближе к 9 выигрывает.','The hand closer to 9 wins.')]},
  casino: { deck:t('52 карты','52 cards'), goal:t('Набрать очки, захватывая карты со стола.','Score points by capturing cards from the table.'), setup:t('Каждому дают по 4 карты, ещё 4 открывают на столе.','Deal 4 cards to each player and 4 face up on the table.'), steps:[t('Карта захватывает равную карту или набор с той же суммой.','A card captures an equal card or a group totaling its value.'),t('Можно строить суммы для последующего захвата.','You may build a value for a later capture.'),t('После колоды считают карты, пики, тузы и специальные карты.','After the deck ends, score cards, spades, aces and special cards.')]},
  'casino-war': { deck:t('6 колод','6 decks'), goal:t('Получить карту старше карты дилера.','Draw a higher card than the dealer.'), setup:t('После ставки игроку и дилеру открывают по одной карте.','After betting, player and dealer each receive one face-up card.'), steps:[t('Старшая карта сразу выигрывает.','The higher card wins immediately.'),t('При равенстве можно сдаться или удвоить ставку и начать спор.','On a tie, surrender or match the bet and go to war.'),t('В споре раздают закрытые карты и снова сравнивают открытые.','War deals burn cards and compares another face-up card.')]},
  'red-dog': { deck:t('6 колод','6 decks'), goal:t('Предсказать, попадёт ли третья карта между двумя первыми.','Predict whether a third rank falls between the first two.'), setup:t('После ставки дилер открывает две карты и определяет разрыв между их достоинствами.','After the bet, two cards are revealed and the rank spread is measured.'), steps:[t('При соседних достоинствах раунд возвращает ставку.','Consecutive ranks push the round.'),t('При паре открывают третью карту: совпадение обычно даёт повышенную выплату.','With a pair, a matching third card usually pays a bonus.'),t('В остальных случаях третья карта внутри разрыва выигрывает; выплата зависит от ширины разрыва.','Otherwise, a third rank inside the spread wins; payout depends on spread size.')]},
};
