import { text as t, type GameRule } from './types.ts';

export const solitaireRules: Record<string, GameRule> = {
  klondike: { deck:t('52 карты','52 cards'), goal:t('Перенести все карты на четыре базы по мастям от туза до короля.','Move all cards to four suit foundations from ace to king.'), setup:t('Семь колонок содержат от 1 до 7 карт; верхние открыты, остальные образуют колоду.','Seven columns hold 1–7 cards; top cards are face up and the rest form the stock.'), steps:[t('В колонках стройте вниз с чередованием цветов.','Build tableau downward in alternating colors.'),t('На пустую колонку кладётся король или ряд от короля.','Only a king or king-led run fills an empty column.'),t('Открывайте колоду и переносите доступные карты на стол или базы.','Draw from stock and move available cards to tableau or foundations.')]},
  spider: { deck:t('104 карты','104 cards'), goal:t('Собрать восемь полных одномастных рядов от короля до туза.','Complete eight same-suit runs from king to ace.'), setup:t('Карты лежат в 10 колонках; оставшиеся сдаются дополнительными рядами.','Deal into 10 columns; remaining cards form extra rows.'), steps:[t('Кладите карту на следующую старшую независимо от масти.','Place a card on the next higher rank regardless of suit.'),t('Перемещать группой можно только правильный одномастный ряд.','Only a packed same-suit sequence moves as a group.'),t('Полный ряд K–A автоматически убирается; перед новой сдачей заполните пустые колонки.','A complete K–A run clears; fill empty columns before dealing a new row.')]},
  freecell: { deck:t('52 карты','52 cards'), goal:t('Собрать четыре базы по мастям от туза до короля.','Build four suit foundations from ace to king.'), setup:t('Все карты открыты в 8 колонках; доступны 4 свободные ячейки.','All cards are face up in 8 columns with 4 free cells.'), steps:[t('В колонках стройте вниз с чередованием цветов.','Build down in alternating colors.'),t('Каждая свободная ячейка временно хранит одну карту.','Each free cell temporarily holds one card.'),t('Длина переносимого ряда ограничена числом пустых ячеек и колонок.','Movable sequence length depends on empty cells and columns.')]},
  pyramid: { deck:t('52 карты','52 cards'), goal:t('Убрать пирамиду парами с суммой 13.','Clear the pyramid using pairs totaling 13.'), setup:t('28 карт образуют пирамиду из 7 рядов, остальные лежат в колоде.','28 cards form a 7-row pyramid; the rest form the stock.'), steps:[t('Можно брать только полностью открытые, не перекрытые карты.','Only uncovered cards are available.'),t('Снимайте пары с суммой 13; король снимается один.','Remove pairs totaling 13; a king removes alone.'),t('Используйте открытую карту сброса вместе с картами пирамиды.','Use the waste card together with pyramid cards.')]},
  yukon: { deck:t('52 карты','52 cards'), goal:t('Перенести карты на четыре базы по мастям от туза до короля.','Move all cards to four suit foundations from ace to king.'), setup:t('Все карты разложены в 7 колонок; отдельной колоды добора нет.','All cards are dealt into 7 columns; there is no stock.'), steps:[t('Стройте вниз с чередованием цветов.','Build down in alternating colors.'),t('Можно переносить любую открытую группу, даже если внутри она не упорядочена.','Any face-up group may move even if internally unordered.'),t('Пустую колонку занимает только король или группа от короля.','Only a king or king-led group fills an empty column.')]},
  scorpion: { deck:t('52 карты','52 cards'), goal:t('Собрать четыре одномастных ряда от короля до туза.','Build four same-suit runs from king to ace.'), setup:t('Карты разложены в 7 колонок, часть закрыта; 3 карты остаются в резерве.','Cards form 7 columns with some face down; 3 remain in reserve.'), steps:[t('Стройте вниз строго по масти.','Build downward in the same suit.'),t('Любую открытую группу можно переносить за её верхнюю карту.','Any face-up group can move by its top card.'),t('Пустую колонку занимает король; резерв раздаётся на первые три колонки.','Only a king fills an empty column; reserve cards go to the first three columns.')]},
  golf: { deck:t('52 карты','52 cards'), goal:t('Убрать все карты семи колонок в сброс.','Clear all cards from the seven tableau columns.'), setup:t('В 7 колонках лежат по 5 открытых карт, остаток образует колоду.','Seven columns hold 5 face-up cards each; the rest form the stock.'), steps:[t('На сброс кладётся доступная карта на один ранг выше или ниже верхней.','Play an exposed card one rank above or below the waste top.'),t('Масть не учитывается; ряды обычно не замыкаются между тузом и королём.','Suits do not matter; ace and king normally do not wrap.'),t('Если хода нет, откройте следующую карту колоды.','When stuck, turn the next stock card.')]},
  'forty-thieves': { deck:t('104 карты','104 cards'), goal:t('Собрать восемь баз по мастям от туза до короля.','Build eight suit foundations from ace to king.'), setup:t('40 открытых карт разложены в 10 колонок по 4; остальные образуют колоду.','Deal 40 face-up cards into 10 columns of 4; the rest form the stock.'), steps:[t('В колонках стройте вниз строго по масти.','Build tableau downward in the same suit.'),t('За ход перемещается только одна карта; пустая колонка принимает любую.','Move one card at a time; any card fills an empty column.'),t('Колода проходит один раз, поэтому планируйте сброс заранее.','The stock is dealt once, so plan waste plays carefully.')]},
  canfield: { deck:t('52 карты','52 cards'), goal:t('Перенести все карты на четыре базы.','Move all cards to four foundations.'), setup:t('13 карт образуют резерв; одна карта задаёт начальный ранг баз, ещё четыре начинают колонки.','A 13-card reserve is made; one card sets the foundation rank and four begin tableau columns.'), steps:[t('Базы строятся по мастям циклически до ранга перед стартовым.','Build foundations by suit, wrapping around ranks.'),t('Колонки строятся вниз с чередованием цветов, также циклически.','Build tableau down in alternating colors, also wrapping ranks.'),t('Пустоты сначала заполняются из резерва, затем из колоды.','Fill empty spaces from reserve first, then stock.')]},
  'clock-solitaire': { deck:t('52 карты','52 cards'), goal:t('Открыть все карты до того, как будут открыты четыре короля.','Reveal every card before all four kings appear.'), setup:t('Карты раскладываются закрыто в 13 стопок: 12 по кругу и одна в центре.','Deal face down into 13 piles: 12 around a clock and one in the center.'), steps:[t('Откройте карту центра и положите её под стопку соответствующего достоинства.','Reveal from the center and place it under the pile matching its rank.'),t('Затем откройте верхнюю карту той стопки и продолжайте цепочку.','Reveal the next card from that pile and continue the chain.'),t('Короли отправляются в центр; четвёртый король завершает игру.','Kings return to the center; the fourth king ends the game.')]},
};
